purge recyclebin;
SET SERVEROUTPUT on;

DECLARE
   super_user number;
BEGIN
   select count(*)
   into super_user from all_users
   where USERNAME = 'SUPER_USER';
   
   IF(super_user > 0) THEN EXECUTE IMMEDIATE 'DROP USER super_user CASCADE'; END IF;
END;
/

CREATE USER super_user IDENTIFIED BY "Superuser123";

ALTER user super_user quota unlimited on data;

GRANT
CREATE ROLE,
CREATE USER, 
DROP USER, 
EXECUTE ANY TYPE, 
DROP ANY TYPE, 
CREATE ANY TYPE, 
ALTER ANY TYPE, 
EXECUTE ANY PROCEDURE, 
ALTER ANY PROCEDURE, 
CREATE ANY PROCEDURE, 
DROP ANY PROCEDURE, 
CREATE PROCEDURE, 
CREATE ANY TABLE, 
CREATE TABLE, 
SELECT ANY TABLE, 
DROP ANY TABLE, 
UPDATE ANY TABLE, 
DELETE ANY TABLE, 
INSERT ANY TABLE, 
ALTER ANY TABLE, 
READ ANY TABLE, 
UNLIMITED TABLESPACE,
CREATE TABLESPACE,
ALTER TABLESPACE,
CREATE TRIGGER, 
CREATE ANY TRIGGER, 
ALTER ANY TRIGGER, 
DROP ANY TRIGGER, 
ALTER ANY INDEX, 
CREATE ANY INDEX, 
DROP ANY INDEX, 
CREATE SESSION, 
DEBUG CONNECT SESSION, 
CREATE SEQUENCE, 
ALTER ANY SEQUENCE, 
CREATE ANY SEQUENCE, 
DROP ANY SEQUENCE,
SELECT ANY SEQUENCE, 
MERGE ANY VIEW, 
DROP ANY VIEW, 
CREATE ANY VIEW,
ALTER ANY ROLE,
GRANT ANY ROLE,
DROP ANY ROLE,
SELECT ANY DICTIONARY,
CONNECT,
RESOURCE
to super_user WITH ADMIN OPTION;